# Generated by Django 2.2.5 on 2019-09-27 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('sub_title', models.CharField(max_length=200)),
                ('descriptions', models.TextField()),
                ('my_name', models.CharField(max_length=100)),
                ('captain_photo', models.ImageField(upload_to='media/captain_photo/')),
                ('capatin_intro', models.TextField()),
            ],
        ),
    ]
