# Generated by Django 2.2.5 on 2019-09-27 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0002_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpage',
            name='site_image2',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='site_image3',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='site_image',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
    ]
