# Generated by Django 2.2.5 on 2019-09-27 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0003_auto_20190927_0753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='capatin_intro',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='about',
            name='descriptions',
            field=models.CharField(max_length=2000),
        ),
    ]
