# Generated by Django 2.2.5 on 2019-09-27 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0004_auto_20190927_0807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='capatin_intro',
        ),
        migrations.AddField(
            model_name='about',
            name='captain_intro',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='descriptions',
            field=models.TextField(blank=True),
        ),
    ]
